/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/fred/Documents/dev/FPGA/myterminal/al_ip/font_ram.v
 ** Date	:	2020 09 03
 ** TD version	:	4.6.14314
\************************************************************/

`timescale 1ns / 1ps

module font_ram ( doa, dia, addra, clka, wea );

	output [15:0] doa;

	input  [15:0] dia;
	input  [14:0] addra;
	input  wea;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(16),
				.ADDR_WIDTH_A(15),
				.DATA_DEPTH_A(20480),
				.DATA_WIDTH_B(16),
				.ADDR_WIDTH_B(15),
				.DATA_DEPTH_B(20480),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../font/extended_videotex.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({16{1'b0}}),
				.addra(addra),
				.addrb({15{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(wea),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule