/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/fred/Documents/dev/FPGA/myterminal/al_ip/pixels.v
 ** Date	:	2020 09 03
 ** TD version	:	4.6.14314
\************************************************************/

`timescale 1ns / 1ps

module pixels ( 
	dia, addra, cea, clka,
	dob, addrb, clkb
);

	output [3:0] dob;


	input  [63:0] dia;
	input  [6:0] addra;
	input  [10:0] addrb;
	input  cea;
	input  clka;
	input  clkb;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(64),
				.DATA_WIDTH_B(4),
				.ADDR_WIDTH_A(7),
				.ADDR_WIDTH_B(11),
				.DATA_DEPTH_A(80),
				.DATA_DEPTH_B(1280),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({4{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(),
				.dob(dob));


endmodule