cursor.mif: cursor-default.png cursor-pointer.png cursor-not-allowed.png cursor-wait.png cursor-move.png cursor-grab.png cursor-crosshair.png cursor-cell.png 
	python3 png_to_mif.py

clean:
	rm -f cursor.mif
