localparam
	CLS                    = 'h01,
	CR                     = 'h0d,
	LF                     = 'h0a,

	ESC                    = 'h1B,

	ESC_SIZE_NORMAL        = 'h4C,
	ESC_SIZE_DOUBLE_HEIGHT = 'h4D,
	ESC_SIZE_DOUBLE_WIDTH  = 'h4E,
	ESC_SIZE_DOUBLE        = 'h4F,

	CSI                    = 'h5B,
	CSI_CURSOR_POSITION    = 'h48,
	CSI_SGR                = 'h6d,
	CSI_SEPARATOR          = 'h3B,
    CSI_ERASE_IN_DISPLAY   = 'h4A,
    CSI_ERASE_IN_LINE      = 'h4B,

	SGR_RESET              = 'd0,
	SGR_BOLD               = 'd1,
	SGR_NORMAL             = 'd22,
	SGR_UNDERLINE_ON       = 'd4,
	SGR_UNDERLINE_OFF      = 'd24,
	SGR_BLINK_SLOW         = 'd5,
	SGR_BLINK_FAST         = 'd6,
	SGR_BLINK_OFF          = 'd25,
	SGR_INVERT_ON          = 'd7,
	SGR_INVERT_OFF         = 'd27,

	SGR_FOREGROUND_0       = 'd30,
	SGR_FOREGROUND_1       = 'd31,
	SGR_FOREGROUND_2       = 'd32,
	SGR_FOREGROUND_3       = 'd33,
	SGR_FOREGROUND_4       = 'd34,
	SGR_FOREGROUND_5       = 'd35,
	SGR_FOREGROUND_6       = 'd36,
	SGR_FOREGROUND_7       = 'd37,
	SGR_FOREGROUND_8       = 'd90,
	SGR_FOREGROUND_9       = 'd91,
	SGR_FOREGROUND_10      = 'd92,
	SGR_FOREGROUND_11      = 'd93,
	SGR_FOREGROUND_12      = 'd94,
	SGR_FOREGROUND_13      = 'd95,
	SGR_FOREGROUND_14      = 'd96,
	SGR_FOREGROUND_15      = 'd97,

	SGR_BACKGROUND_0       = 'd40,
	SGR_BACKGROUND_1       = 'd41,
	SGR_BACKGROUND_2       = 'd42,
	SGR_BACKGROUND_3       = 'd43,
	SGR_BACKGROUND_4       = 'd44,
	SGR_BACKGROUND_5       = 'd45,
	SGR_BACKGROUND_6       = 'd46,
	SGR_BACKGROUND_7       = 'd47,
	SGR_BACKGROUND_8       = 'd100,
	SGR_BACKGROUND_9       = 'd101,
	SGR_BACKGROUND_10      = 'd102,
	SGR_BACKGROUND_11      = 'd103,
	SGR_BACKGROUND_12      = 'd104,
	SGR_BACKGROUND_13      = 'd105,
	SGR_BACKGROUND_14      = 'd106,
	SGR_BACKGROUND_15      = 'd107
;
